// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azzttdpzhhjwzsqhiccp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6enR0ZHB6aGhqd3pzcWhpY2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDM1NzQsImV4cCI6MjA3MzgxOTU3NH0.q0EZ5a3mo1wGgxK0rf8CsZFlKzLRjHCMZ_pRznmJyQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});